#===-- lib/Transformation/Makefile ---------------------------------------===#
#
#                     The LAV Software Verification Tool
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===----------------------------------------------------------------------===#

LEVEL=../..

PARALLEL_DIRS=
LIBRARYNAME=transformation
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common
