#===-- lib/Expression/Makefile -------------------------------------------===#
#
#                     The LAV Software Verification Tool
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===----------------------------------------------------------------------===#

#
# Relative path to the top of the source tree.
#
LEVEL=../..

PARALLEL_DIRS=
LIBRARYNAME=expression
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common

LIBS += -lpthread

