#===-- lib/Makefile --------------------------------------------------===#
#
#                     The LAV Software Verification Tool
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===----------------------------------------------------------------------===#

LEVEL=..

PARALLEL_DIRS= Expression Misc Core Transformation Solvers TestLAV Threads 

include $(LEVEL)/Makefile.common
